#!/bin/bash

# Error handling function
handle_error() {
  echo "Execution error on line $1. Exiting..."
  exit 1
}

# Trap errors and call the error handler
trap 'handle_error $LINENO' ERR

[ "$(id -u)" -ne "0" ] && echo "you are not root: use 'sudo -s'" && exit



netcycle()
{
echo "press r to restart network or enter to exit"
read nmrestart
if [ "$nmrestart" == "r" ]; then
	ip route flush
       nmcli con down $conname1 && nmcli con up $conname1	
       nmcli con down $conname2 && nmcli con up $conname2	
fi
}


### set iface variables

ifnum=1
connum=1
for i in $(ip link show | awk -F: '/^[0-9]+: / {print $2}' | sed 's/ //g' | grep -v lo)
do
	eval "iface${ifnum}=$i"
	con_name=$(nmcli con show | grep "$(eval echo \${iface${ifnum}})" | awk -F" " '{print $1}')
	eval "conname${connum}=\"$con_name\""
	((ifnum++))
	((connum++))
done

### check for netcycle commmand
[ "$1" = "netcycle" ] && netcycle && exit

### get user input
newhost=
echo -n "enter new hostname >"
read newhost

echo -n "enter management ip >"
read mgmtip
while [[ ! "$mgmtip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$ ]]; do
    echo "wrong format"
    echo -n "enter management IP (e.g., 172.22.3.30/24): "
    read mgmtip
done

echo -n "enter server network ip >"
read servip

while [[ ! "$servip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$ ]]; do
    echo "wrong format"
    echo -n "enter management IP (e.g., 172.22.3.30/24): "
    read servip
done
echo ""
echo "----------------------------------------------------"
echo "hostname will be set to:           $newhost"
echo "----------------------------------------------------"
echo "management ip will be set to:      $mgmtip"
echo "management interface:              $iface1"
echo "management connection name:        $conname1"
echo "----------------------------------------------------"
echo "server network ip will be set to:  $servip"
echo "server network interface:          $iface2"
echo "server network connection name:    $conname2"
echo "----------------------------------------------------"
echo -n "press enter to continue or x to exit > "
read abort
[ "$abort" == "x" ] && exit

### set hostname
hostnamectl hostname $newhost
echo "hostname has been set to $(hostnamectl hostname)"

### $conname1 iface $iface1

# remove current IPs from $iface1
for nip in $(ip addr show dev $iface1 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{2}') 
do
	#echo $nip
#	nmcli con mod $conname1 -ipv4.gateway $(echo "$(echo -n $nip | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}').1") -ipv4.addresses $nip ipv4.method auto 
	nmcli con mod $conname1 ipv4.gateway ""  -ipv4.addresses $nip ipv4.method auto 
done

# set new IPs
mgateip=$(echo "$(echo -n $mgmtip | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}').1")
nmcli con mod $conname1 ipv4.addresses $mgmtip ipv4.gateway $mgateip ipv4.method manual ipv4.ignore-auto-routes yes ipv4.never-default yes
echo "management network IP set to $mgmtip"
echo "management network gateway IP set to $mgateip"



#### server network iface $iface2

# remove current IPs from $iface2
for sip in $(ip addr show dev $iface2 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}') 
do 
	#nmcli con mod $conname2 -ipv4.gateway $(echo "$(echo -n $sip | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}').1") -ipv4.addresses $sip ipv4.method auto
	nmcli con mod $conname2 ipv4.gateway "" -ipv4.addresses $sip ipv4.method auto
done

# set new IPs
sgateip=$(echo "$(echo -n $servip | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}').1")
nmcli con mod $conname2 ipv4.addresses $servip ipv4.gateway $sgateip ipv4.method manual ipv4.ignore-auto-routes yes ipv4.never-default yes
echo "server network IP set to $servip"
echo "server network gateway IP set to $sgateip"

modrouteips()
{
### modify iface rule automation for iface $iface1


# replace interface IP with management IP for $iface1
base_mgmtip=$(echo $mgmtip | sed 's/\/24//')
escaped_mgmtip=$(echo "$base_mgmtip" | sed 's/[&/\]/\\&/g')
sed -i "/$iface1/,/^\s*;/ {
    s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[^1][0-9]\{1,2\}/$escaped_mgmtip/g
}" /etc/NetworkManager/dispatcher.d/99-add-routes

# replace gateway IP for iface $iface1
escaped_base_ip=$(echo "$mgmtip" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
escaped_target_ip=$(echo "${escaped_base_ip}.1" | sed 's/[&/\]/\\&/g')
# echo $escaped_target_ip
sed -i "/$iface1/,/^\s*#/{
    s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.1/$escaped_target_ip/g
}" /etc/NetworkManager/dispatcher.d/99-add-routes
echo "network manager route automation updated for mamagement interface $iface1"

# replace interface IP with server network IP for $iface2
base_servip=$(echo $servip | sed 's/\/24//')
escaped_servip=$(echo "$base_servip" | sed 's/[&/\]/\\&/g')
sed -i "/$iface2/,/^\s*;/ {
    s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[^1][0-9]\{1,2\}/$escaped_servip/g
}" /etc/NetworkManager/dispatcher.d/99-add-routes

# replace gateway IP for iface $iface2
escaped_base_servip=$(echo "$servip" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
escaped_target_servip=$(echo "${escaped_base_servip}.1" | sed 's/[&/\]/\\&/g')

sed -i "/$iface2/,/^\s*#/{
    s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.1/$escaped_target_servip/g
}" /etc/NetworkManager/dispatcher.d/99-add-routes
echo "server manager route automation updated for mamagement interface $iface2"
}

newroutefile()
{

### check for ip forward
if [ "$(cat /proc/sys/net/ipv4/ip_forward)" == "0" ]; then
	echo "1" > /proc/sys/net/ipv4/ip_forward
	grep -qFo "net.ipv4.ip_forward = 1" /etc/sysctl.d/99-sysctl.conf || echo "net.ipv4.ip_forward = 1" | tee -a /etc/sysctl.d/99-sysctl.conf
	echo "enabled ip forwarding"
else
	echo "ip forwarding is enabled"
fi

### check for route tables
if grep -qEo "[0-9]{1,5} $(echo $conname1)_table" /etc/iproute2/rt_tables; then
    echo "the table $(echo $conname1)_table exists"
else
    echo "100 $(echo $conname1)_table" >> /etc/iproute2/rt_tables;
    echo "added $(echo $conname1)_table"
fi

if grep -qEo "[0-9]{1,5} $(echo $conname2)_table" /etc/iproute2/rt_tables; then
    echo "the table $(echo $conname2)_table exists"
else
    echo "110 $(echo $conname2)_table" >> /etc/iproute2/rt_tables;
    echo "added $(echo $conname2)_table"
fi

### create route automation script for NetworkManager
base_mgmtip=$(echo $mgmtip | sed 's/\/24//')
base_servip=$(echo $servip | sed 's/\/24//')

echo "#!/bin/bash

# place in /etc/NetworkManager/dispatcher.d/
# Check if the interface is up and apply routing rules accordingly
if [ \"\$2\" == \"up\" ]; then
  case \"\$1\" in
    # For $iface1 interface
    $iface1)
      # Add routing rule and routes for $iface1
      ip route add default via $mgateip dev $iface1
      ip rule add priority 100 from $base_mgmtip lookup $(echo $conname1)_table
      ip route add $mgateip dev $iface1
      ip route add default via $mgateip dev $iface1 table $(echo $conname1)_table
      ;;
    # For $iface2 interface
    $iface2)
      # Add routing rule and routes for $iface2
      ip rule add priority 110 from $base_servip lookup $(echo $conname2)_table
      ip route add $sgateip dev $iface2
      ip route add default via $sgateip dev $iface2 table $(echo $conname2)_table
      ;;
  esac
fi" > /etc/NetworkManager/dispatcher.d/99-add-routes
chmod +x /etc/NetworkManager/dispatcher.d/99-add-routes
echo "routes for $iface1 and $iface2 have been added to the NetworkManager config"
}

if [ -f /etc/NetworkManager/dispatcher.d/99-add-route ]; then
	modrouteips	
else
	newroutefile
fi

netcycle
