#!/bin/bash

# fip: Script to manage OpenStack floating IPs remotely

set -e

# Default values
CONTROLLER_IP=172.22.3.21
OPENRC=stacked-openrc

# Usage function
usage() {
    cat << EOF
Usage: fip [OPTIONS]

Manage OpenStack floating IPs remotely.

Options:
    -l    List unused floating IPs
    -d    Delete unused floating IPs
    -h    Display this help message

Examples:
    fip -l    List all unassigned floating IPs
    fip -d    Delete all unassigned floating IPs

EOF
}

# Function to delete unused floating IPs
delete_unused_fips() {
    ssh "$CONTROLLER_IP" bash <<EOF
set -e
source ~/cos-node-setup/$OPENRC

fip_list=$(openstack floating ip list -c 'ID' -c 'Fixed IP Address' -f value | grep None | awk -F" " '{ printf "%s ", $1 }')

if [ -z "$fip_list" ]; then
    echo "No unused floating IPs to delete."
else
    echo "Deleting unused floating IPs..."
    for fip_id in $fip_list ; do
        echo "Deleting floating IP: $fip_id"
        openstack floating ip delete $fip_id
    done
    echo "Done."
fi
EOF
}

# Function to list unused floating IPs
list_unused_fips() {
    ssh "$CONTROLLER_IP" bash <<EOF
set -e
source ~/cos-node-setup/$OPENRC

echo "Unassigned Floating IPs:"
echo ""

# Get network list for ID to name mapping
declare -A network_names
while read -r net_id net_name; do
    if [ -n "\$net_id" ] && [ -n "\$net_name" ]; then
        network_names["\$net_id"]="\$net_name"
    fi
done < <(openstack network list -c 'ID' -c 'Name' -f value)

# Print header
printf "%-38s %-20s %-20s\n" "ID" "Floating IP Address" "Floating Network"
printf "%-38s %-20s %-20s\n" "------------------------------------" "-------------------" "-------------------"

# Get floating IP list and format output
openstack floating ip list -c 'ID' -c 'Floating IP Address' -c 'Fixed IP Address' -c 'Floating Network' -f value | grep None | while read -r fip_id floating_ip fixed_ip network_id; do
    network_name="\${network_names[\$network_id]:-\$network_id}"
    printf "%-38s %-20s %-20s\n" "\$fip_id" "\$floating_ip" "\$network_name"
done
EOF
}

# Parse command line options
if [ $# -eq 0 ]; then
    usage
    exit 0
fi

while getopts "ldh" opt; do
    case $opt in
        l)
            list_unused_fips
            ;;
        d)
            delete_unused_fips
            ;;
        h)
            usage
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            exit 1
            ;;
    esac
done